name: Release

permissions:
  contents: write
  pull-requests: write

env:
  PANDOC_VERSION: 3.1.1.0

on:
  pull_request:
    types:
      - closed
    branches:
      - release

jobs:
  release-pr:
    # guard against running on forks
    if: github.repository == 'TTT-2/TTT2'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check if PR was merged
        uses: actions-ecosystem/action-release-label@v1
        id: release-label
        if: ${{ github.event.pull_request.merged == true }}

      - name: Get latest tag if a release label exists on last merged PR
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}

      - name: Bump semver tag according to detected release label
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}

      - name: Generate app token
        uses: actions/create-github-app-token@v1
        id: generate-token
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Add release heading (version, tag link and date) to CHANGELOG.md
        run: 'sed -i "/^## Unreleased$/a\\\n## [v${TTT2_VERSION}](https://github.com/TTT-2/TTT2/tree/v${TTT2_VERSION}) ($(date +%Y-%m-%d))" CHANGELOG.md'
        if: ${{ steps.release-label.outputs.level != null }}
        env:
          TTT2_VERSION: ${{ steps.bump-semver.outputs.new_version }}

      - name: Generate html from changelog for cl_changes.lua
        uses: "docker://docker.io/pandoc/core:${PANDOC_VERSION}"
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          args: >-
            --output=output.html
            --read=markdown_strict
            <(sed -e '1,/^## \[/d' -e '/^## \[/,$d' CHANGELOG.md)

      - name: Stuff lua stuff around html changes
        run: |
          sed -i
          -e "1i \\AddChange(\n"TTT2 Base - ${TTT2_VERSION}",\n[["
          -e "\$a\\\\n]],\nos.time({ year = $(date +%Y), month = $(date +%m), day = $(date +%d) })\n)\n"
          output.html
        env:
          TTT2_VERSION: ${{ steps.bump-semver.outputs.new_version }}

      - name: Update cl_changes.lua
        run: "sed -i '/--#endofchanges/e cat output.html' gamemodes/terrortown/gamemode/client/cl_changes.lua"
        if: ${{ steps.release-label.outputs.level != null }}
        env:
          TTT2_VERSION: ${{ steps.bump-semver.outputs.new_version }}

      - name: Update GM.Version in sh_init.lua
        run: 'sed -i "s/^GM\.Version = \".*\"$/GM\.Version = \"${TTT2_VERSION}\"/" gamemodes/terrortown/gamemode/shared/sh_init.lua'
        if: ${{ steps.release-label.outputs.level != null }}
        env:
          TTT2_VERSION: ${{ steps.bump-semver.outputs.new_version }}

      - name: Create Pull Request
        id: ci-release
        uses: peter-evans/create-pull-request@v6
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          token: ${{ steps.generate-token.outputs.token }}
          add-paths: |
            "CHANGELOG.md"
            "gamemodes/terrortown/gamemode/client/cl_changes.lua"
            "gamemodes/terrortown/gamemode/shared/sh_init.lua"
          commit-message: "Release ${TTT2_VERSION}"
          branch: ci-automated-release
          title: "[Release] ${TTT2_VERSION}"
          body: |
            Auto-generated by github actions.
            Please do not add a `release/*` label to this PR.
        env:
          TTT2_VERSION: ${{ steps.bump-semver.outputs.new_version }}
